import type { ThemeProfile } from "./types.ts";

/**
 * Embedded built-ins are the offline source of truth. All profiles are dark;
 * the default "dark" entry is intentionally styled differently from the host
 * application's stock dark theme so an assigned child never mirrors the
 * parent's look unless the user deliberately reuses those exact tokens.
 */

const DARK: ThemeProfile = {
  themeId: "dark",
  name: "Deep Space",
  colorMode: "truecolor",
  vars: {
    cyan: "#89ddff",
    blue: "#82aaff",
    green: "#c3e88d",
    red: "#f07178",
    yellow: "#ffcb6b",
    purple: "#c792ea",
    orange: "#f78c6c",
    text: "#d6deeb",
    gray: "#8a919e",
    dimGray: "#65737e",
    darkGray: "#3b4261",
    selectedBg: "#2b3249",
    userMsgBg: "#1f2438",
    toolPendingBg: "#232941",
    toolSuccessBg: "#1f2d38",
    toolErrorBg: "#38202c",
    customMsgBg: "#252a44",
  },
  colors: {
    accent: "blue",
    border: "darkGray",
    borderAccent: "cyan",
    borderMuted: "dimGray",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "text",
    toolOutput: "gray",
    mdHeading: "yellow",
    mdLink: "blue",
    mdLinkUrl: "dimGray",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "gray",
    mdQuote: "gray",
    mdQuoteBorder: "gray",
    mdHr: "gray",
    mdListBullet: "orange",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "#5f7a97",
    syntaxKeyword: "purple",
    syntaxFunction: "blue",
    syntaxVariable: "text",
    syntaxString: "green",
    syntaxNumber: "orange",
    syntaxType: "yellow",
    syntaxOperator: "cyan",
    syntaxPunctuation: "gray",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#16161e",
    cardBg: "#1c2130",
    infoBg: "#3a3328",
  },
};

const ATOM_DARK: ThemeProfile = {
  themeId: "atom-dark",
  name: "Atom One Dark",
  colorMode: "truecolor",
  vars: {
    cyan: "#56b6c2",
    blue: "#61afef",
    green: "#98c379",
    red: "#e06c75",
    yellow: "#e5c07b",
    purple: "#c678dd",
    orange: "#d19a66",
    text: "#abb2bf",
    gray: "#5c6370",
    dimGray: "#4b5263",
    darkGray: "#3a3f4b",
    selectedBg: "#3e4451",
    userMsgBg: "#2c313a",
    toolPendingBg: "#333842",
    toolSuccessBg: "#2d3340",
    toolErrorBg: "#40313a",
    customMsgBg: "#2e3440",
  },
  colors: {
    accent: "blue",
    border: "darkGray",
    borderAccent: "cyan",
    borderMuted: "dimGray",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "text",
    toolOutput: "gray",
    mdHeading: "orange",
    mdLink: "blue",
    mdLinkUrl: "dimGray",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "gray",
    mdQuote: "gray",
    mdQuoteBorder: "gray",
    mdHr: "gray",
    mdListBullet: "blue",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "gray",
    syntaxKeyword: "purple",
    syntaxFunction: "blue",
    syntaxVariable: "#e06c75",
    syntaxString: "green",
    syntaxNumber: "orange",
    syntaxType: "yellow",
    syntaxOperator: "cyan",
    syntaxPunctuation: "text",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#282c34",
    cardBg: "#21252b",
    infoBg: "#3a3328",
  },
};

const MONOKAI: ThemeProfile = {
  themeId: "monokai",
  name: "Monokai",
  colorMode: "truecolor",
  vars: {
    green: "#a6e22e",
    pink: "#f92672",
    orange: "#fd971f",
    yellow: "#e6db74",
    purple: "#ae81ff",
    cyan: "#66d9ef",
    text: "#f8f8f2",
    gray: "#75715e",
    dimGray: "#59594c",
    darkGray: "#3e3d32",
    selectedBg: "#49483e",
    userMsgBg: "#323330",
    toolPendingBg: "#3b3a35",
    toolSuccessBg: "#31392c",
    toolErrorBg: "#402a2e",
    customMsgBg: "#36342b",
  },
  colors: {
    accent: "green",
    border: "darkGray",
    borderAccent: "orange",
    borderMuted: "dimGray",
    success: "green",
    error: "pink",
    warning: "orange",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "text",
    toolOutput: "gray",
    mdHeading: "orange",
    mdLink: "cyan",
    mdLinkUrl: "dimGray",
    mdCode: "pink",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "gray",
    mdQuote: "gray",
    mdQuoteBorder: "gray",
    mdHr: "gray",
    mdListBullet: "orange",
    toolDiffAdded: "green",
    toolDiffRemoved: "pink",
    toolDiffContext: "gray",
    syntaxComment: "gray",
    syntaxKeyword: "pink",
    syntaxFunction: "green",
    syntaxVariable: "orange",
    syntaxString: "yellow",
    syntaxNumber: "purple",
    syntaxType: "cyan",
    syntaxOperator: "pink",
    syntaxPunctuation: "gray",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "green",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "pink",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#272822",
    cardBg: "#1e1f1c",
    infoBg: "#3a3328",
  },
};

const DRACULA: ThemeProfile = {
  themeId: "dracula",
  name: "Dracula",
  colorMode: "truecolor",
  vars: {
    cyan: "#8be9fd",
    green: "#50fa7b",
    red: "#ff5555",
    yellow: "#f1fa8c",
    purple: "#bd93f9",
    pink: "#ff79c6",
    orange: "#ffb86c",
    comment: "#6272a4",
    text: "#f8f8f2",
    gray: "comment",
    dimGray: "#565f89",
    darkGray: "#44475a",
    selectedBg: "#44475a",
    userMsgBg: "#2b2d3d",
    toolPendingBg: "#343746",
    toolSuccessBg: "#283a3d",
    toolErrorBg: "#3a2d3d",
    customMsgBg: "#2f3145",
  },
  colors: {
    accent: "purple",
    border: "darkGray",
    borderAccent: "cyan",
    borderMuted: "comment",
    success: "green",
    error: "red",
    warning: "orange",
    muted: "comment",
    dim: "dimGray",
    text: "text",
    thinkingText: "comment",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "pink",
    toolTitle: "text",
    toolOutput: "comment",
    mdHeading: "pink",
    mdLink: "cyan",
    mdLinkUrl: "comment",
    mdCode: "purple",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "comment",
    mdQuote: "comment",
    mdQuoteBorder: "comment",
    mdHr: "comment",
    mdListBullet: "orange",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "comment",
    syntaxComment: "comment",
    syntaxKeyword: "pink",
    syntaxFunction: "green",
    syntaxVariable: "cyan",
    syntaxString: "orange",
    syntaxNumber: "orange",
    syntaxType: "cyan",
    syntaxOperator: "pink",
    syntaxPunctuation: "comment",
    thinkingOff: "comment",
    thinkingMinimal: "comment",
    thinkingLow: "cyan",
    thinkingMedium: "green",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "pink",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#282a36",
    cardBg: "#21222c",
    infoBg: "#3a3328",
  },
};

const NORD: ThemeProfile = {
  themeId: "nord",
  name: "Nord",
  colorMode: "truecolor",
  vars: {
    cyan: "#88c0d0",
    blue: "#81a1c1",
    deepBlue: "#5e81ac",
    teal: "#8fbcbb",
    green: "#a3be8c",
    red: "#bf616a",
    yellow: "#ebcb8b",
    purple: "#b48ead",
    orange: "#d08770",
    text: "#d8dee9",
    gray: "#7b88a1",
    dimGray: "#4c566a",
    darkGray: "#434c5e",
    selectedBg: "#434c5e",
    userMsgBg: "#353c4a",
    toolPendingBg: "#3b4252",
    toolSuccessBg: "#3b4252",
    toolErrorBg: "#453a41",
    customMsgBg: "#3b4252",
  },
  colors: {
    accent: "cyan",
    border: "darkGray",
    borderAccent: "blue",
    borderMuted: "dimGray",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "text",
    toolOutput: "gray",
    mdHeading: "teal",
    mdLink: "blue",
    mdLinkUrl: "dimGray",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "dimGray",
    mdQuote: "gray",
    mdQuoteBorder: "dimGray",
    mdHr: "dimGray",
    mdListBullet: "deepBlue",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "#616e88",
    syntaxKeyword: "deepBlue",
    syntaxFunction: "blue",
    syntaxVariable: "text",
    syntaxString: "green",
    syntaxNumber: "orange",
    syntaxType: "teal",
    syntaxOperator: "#81a1c1",
    syntaxPunctuation: "gray",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#2e3440",
    cardBg: "#3b4252",
    infoBg: "#3a3328",
  },
};

const SOLARIZED_DARK: ThemeProfile = {
  themeId: "solarized-dark",
  name: "Solarized Dark",
  colorMode: "truecolor",
  vars: {
    cyan: "#2aa198",
    blue: "#268bd2",
    green: "#859900",
    red: "#dc322f",
    yellow: "#b58900",
    orange: "#cb4b16",
    violet: "#6c71c4",
    magenta: "#d33682",
    text: "#93a1a1",
    brightText: "#eee8d5",
    gray: "#586e75",
    dimGray: "#465458",
    darkGray: "#0d4756",
    selectedBg: "#0d4756",
    userMsgBg: "#073642",
    toolPendingBg: "#0a4150",
    toolSuccessBg: "#0a4142",
    toolErrorBg: "#46231f",
    customMsgBg: "#0c3f4a",
  },
  colors: {
    accent: "cyan",
    border: "darkGray",
    borderAccent: "blue",
    borderMuted: "gray",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "brightText",
    userMessageText: "brightText",
    customMessageText: "brightText",
    customMessageLabel: "magenta",
    toolTitle: "brightText",
    toolOutput: "gray",
    mdHeading: "blue",
    mdLink: "blue",
    mdLinkUrl: "gray",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "gray",
    mdQuote: "gray",
    mdQuoteBorder: "gray",
    mdHr: "gray",
    mdListBullet: "violet",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "#586e75",
    syntaxKeyword: "green",
    syntaxFunction: "blue",
    syntaxVariable: "text",
    syntaxString: "cyan",
    syntaxNumber: "orange",
    syntaxType: "yellow",
    syntaxOperator: "magenta",
    syntaxPunctuation: "#839496",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "violet",
    thinkingXhigh: "magenta",
    thinkingMax: "orange",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#002b36",
    cardBg: "#073642",
    infoBg: "#3a3328",
  },
};

const GRUVBOX_DARK: ThemeProfile = {
  themeId: "gruvbox-dark",
  name: "Gruvbox Dark",
  colorMode: "truecolor",
  vars: {
    green: "#b8bb26",
    aqua: "#8ec07c",
    blue: "#83a598",
    red: "#fb4934",
    yellow: "#fabd2f",
    orange: "#fe8019",
    purple: "#d3869b",
    text: "#ebdbb2",
    gray: "#928374",
    dimGray: "#665c54",
    darkGray: "#3c3836",
    selectedBg: "#504945",
    userMsgBg: "#32302f",
    toolPendingBg: "#3c3836",
    toolSuccessBg: "#32392a",
    toolErrorBg: "#3c2b27",
    customMsgBg: "#3a3530",
  },
  colors: {
    accent: "orange",
    border: "darkGray",
    borderAccent: "yellow",
    borderMuted: "dimGray",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "text",
    toolOutput: "gray",
    mdHeading: "yellow",
    mdLink: "blue",
    mdLinkUrl: "dimGray",
    mdCode: "aqua",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "gray",
    mdQuote: "gray",
    mdQuoteBorder: "gray",
    mdHr: "gray",
    mdListBullet: "orange",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "gray",
    syntaxKeyword: "red",
    syntaxFunction: "green",
    syntaxVariable: "text",
    syntaxString: "green",
    syntaxNumber: "purple",
    syntaxType: "yellow",
    syntaxOperator: "orange",
    syntaxPunctuation: "#bdae93",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "aqua",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#282828",
    cardBg: "#1d2021",
    infoBg: "#3a3328",
  },
};

const TOKYO_NIGHT: ThemeProfile = {
  themeId: "tokyo-night",
  name: "Tokyo Night",
  colorMode: "truecolor",
  vars: {
    cyan: "#7dcfff",
    teal: "#73daca",
    blue: "#7aa2f7",
    green: "#9ece6a",
    red: "#f7768e",
    yellow: "#e0af68",
    orange: "#ff9e64",
    purple: "#bb9af7",
    comment: "#565f89",
    text: "#a9b1d6",
    brightText: "#c0caf5",
    gray: "comment",
    dimGray: "#414868",
    darkGray: "#292e42",
    selectedBg: "#292e42",
    userMsgBg: "#1f2233",
    toolPendingBg: "#24283b",
    toolSuccessBg: "#20303a",
    toolErrorBg: "#37273a",
    customMsgBg: "#22263c",
  },
  colors: {
    accent: "blue",
    border: "darkGray",
    borderAccent: "cyan",
    borderMuted: "comment",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "comment",
    dim: "dimGray",
    text: "text",
    thinkingText: "comment",
    searchMatchText: "brightText",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "purple",
    toolTitle: "brightText",
    toolOutput: "comment",
    mdHeading: "orange",
    mdLink: "blue",
    mdLinkUrl: "comment",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "comment",
    mdQuote: "comment",
    mdQuoteBorder: "comment",
    mdHr: "comment",
    mdListBullet: "teal",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "comment",
    syntaxComment: "comment",
    syntaxKeyword: "purple",
    syntaxFunction: "blue",
    syntaxVariable: "brightText",
    syntaxString: "green",
    syntaxNumber: "orange",
    syntaxType: "cyan",
    syntaxOperator: "teal",
    syntaxPunctuation: "comment",
    thinkingOff: "dimGray",
    thinkingMinimal: "comment",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#1a1b26",
    cardBg: "#16161e",
    infoBg: "#3a3328",
  },
};

const CATPPUCCIN_MOCHA: ThemeProfile = {
  themeId: "catppuccin-mocha",
  name: "Catppuccin Mocha",
  colorMode: "truecolor",
  vars: {
    sky: "#89dceb",
    blue: "#89b4fa",
    lavender: "#b4befe",
    green: "#a6e3a1",
    teal: "#94e2d5",
    red: "#f38ba8",
    peach: "#fab387",
    yellow: "#f9e2af",
    mauve: "#cba6f7",
    pink: "#f5c2e7",
    overlay: "#6c7086",
    subtext: "#a6adc8",
    text: "#cdd6f4",
    gray: "overlay",
    dimGray: "#45475a",
    darkGray: "#313244",
    selectedBg: "#45475a",
    userMsgBg: "#26263a",
    toolPendingBg: "#302d46",
    toolSuccessBg: "#273539",
    toolErrorBg: "#3d2b39",
    customMsgBg: "#2c2a44",
  },
  colors: {
    accent: "mauve",
    border: "darkGray",
    borderAccent: "lavender",
    borderMuted: "overlay",
    success: "green",
    error: "red",
    warning: "peach",
    muted: "subtext",
    dim: "dimGray",
    text: "text",
    thinkingText: "overlay",
    searchMatchText: "text",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "pink",
    toolTitle: "text",
    toolOutput: "overlay",
    mdHeading: "peach",
    mdLink: "blue",
    mdLinkUrl: "overlay",
    mdCode: "sky",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "overlay",
    mdQuote: "subtext",
    mdQuoteBorder: "overlay",
    mdHr: "overlay",
    mdListBullet: "teal",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "overlay",
    syntaxComment: "overlay",
    syntaxKeyword: "mauve",
    syntaxFunction: "blue",
    syntaxVariable: "text",
    syntaxString: "green",
    syntaxNumber: "peach",
    syntaxType: "yellow",
    syntaxOperator: "sky",
    syntaxPunctuation: "subtext",
    thinkingOff: "dimGray",
    thinkingMinimal: "overlay",
    thinkingLow: "sky",
    thinkingMedium: "blue",
    thinkingHigh: "mauve",
    thinkingXhigh: "pink",
    thinkingMax: "red",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#1e1e2e",
    cardBg: "#181825",
    infoBg: "#3a3328",
  },
};

const GITHUB_DARK: ThemeProfile = {
  themeId: "github-dark",
  name: "GitHub Dark",
  colorMode: "truecolor",
  vars: {
    cyan: "#39c5cf",
    blue: "#58a6ff",
    green: "#56d364",
    red: "#f85149",
    yellow: "#d29922",
    orange: "#f78166",
    purple: "#bc8cff",
    pink: "#db61a2",
    comment: "#484f58",
    text: "#c9d1d9",
    brightText: "#e6edf3",
    gray: "#8b949e",
    dimGray: "#484f58",
    darkGray: "#21262d",
    selectedBg: "#283042",
    userMsgBg: "#141a24",
    toolPendingBg: "#1b222e",
    toolSuccessBg: "#152a26",
    toolErrorBg: "#33262a",
    customMsgBg: "#182030",
  },
  colors: {
    accent: "blue",
    border: "darkGray",
    borderAccent: "cyan",
    borderMuted: "comment",
    success: "green",
    error: "red",
    warning: "yellow",
    muted: "gray",
    dim: "dimGray",
    text: "text",
    thinkingText: "gray",
    searchMatchText: "brightText",
    userMessageText: "text",
    customMessageText: "text",
    customMessageLabel: "pink",
    toolTitle: "brightText",
    toolOutput: "gray",
    mdHeading: "orange",
    mdLink: "blue",
    mdLinkUrl: "gray",
    mdCode: "cyan",
    mdCodeBlock: "green",
    mdCodeBlockBorder: "comment",
    mdQuote: "gray",
    mdQuoteBorder: "comment",
    mdHr: "comment",
    mdListBullet: "purple",
    toolDiffAdded: "green",
    toolDiffRemoved: "red",
    toolDiffContext: "gray",
    syntaxComment: "#6e7681",
    syntaxKeyword: "red",
    syntaxFunction: "purple",
    syntaxVariable: "orange",
    syntaxString: "#a5d6ff",
    syntaxNumber: "blue",
    syntaxType: "yellow",
    syntaxOperator: "#d2a8ff",
    syntaxPunctuation: "gray",
    thinkingOff: "dimGray",
    thinkingMinimal: "gray",
    thinkingLow: "cyan",
    thinkingMedium: "blue",
    thinkingHigh: "purple",
    thinkingXhigh: "orange",
    thinkingMax: "pink",
    bashMode: "green",
    selectedBg: "selectedBg",
    scrollbarThumb: "selectedBg",
    searchMatchBg: "selectedBg",
    userMessageBg: "userMsgBg",
    customMessageBg: "customMsgBg",
    toolPendingBg: "toolPendingBg",
    toolSuccessBg: "toolSuccessBg",
    toolErrorBg: "toolErrorBg",
  },
  export: {
    pageBg: "#0d1117",
    cardBg: "#161b22",
    infoBg: "#3a3328",
  },
};

/** Embedded built-ins are the offline recovery source of truth. */
export const BUILTIN_THEME_PROFILES: readonly ThemeProfile[] = Object.freeze([
  DARK,
  ATOM_DARK,
  DRACULA,
  NORD,
  MONOKAI,
  GRUVBOX_DARK,
  TOKYO_NIGHT,
  CATPPUCCIN_MOCHA,
  SOLARIZED_DARK,
  GITHUB_DARK,
]);
export const BUILTIN_THEME_IDS = Object.freeze(BUILTIN_THEME_PROFILES.map((profile) => profile.themeId));
export const DEFAULT_THEME_ID = "dark";
